package util.enums;

public enum PropertyType {
    BROWSERSTACK_USERNAME, BROWSERSTACK_ACCESS_KEY, BROWSERSTACK_LOCAL_IDENTIFIER, TARGET, LOCAL, BASE_URI, PORT,
    VISA_MOCK_URI, CC_MOCK_ACS_URI, APPLEPAY_MOCK_URI, GATEWAY_MOCK_URI, WEBSERVICES_DOMAIN
}